apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: workspace
  namespace:   {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: ssl
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host:  {{ .Values.host }}
      http:
        paths:
          - path: /workspace
            backend:
              serviceName: workspaceservice
              servicePort: 80